### PR TITLE
removed the -nolatches option in run_fpga_flow script

### PR DESCRIPTION
**Pull request by rakeshm75**
> ### Motivate of the pull request
>removed the -nolatches option in run_fpga_flow script to supports latch implementation

### CODE REVIEW

**Comment by tangxifan** [comment]
@rakeshm75 Can you look into the CI errors?

**Comment by tangxifan** [comment]
@rakeshm75 The changes make sense to me. Since it is hardcoded for QuickLogic's K6N10 recipe. Should we add a note to the documentation? Also, would you mind adding a dedicated test case for the k6n10 recipe (currently all the quicklogic test cases are  for k4n8 recipe)

**Comment by tangxifan** [comment]
@ganeshgore Can you also check the modification on the python scripts (since you are the code owner)?

**Comment by tpagarani** [comment]
> 

@tangxifan to add a testcase for k6n10f, we have put VPR and OpenFPGA architecture files in OpenFPGA. Are you ok with that?

**Comment by tangxifan** [comment]
> > 
> 
> @tangxifan, To add a testcase for k6n10f, we have put VPR and OpenFPGA architecture files in OpenFPGA. Are you ok with that?

@tpagarani It is o.k. for me as long as it does not require NDA. Can you point me to the arch files if they are already in?

**Comment by tpagarani** [comment]
> > > 
> > 
> > 
> > @tangxifan, To add a testcase for k6n10f, we have put VPR and OpenFPGA architecture files in OpenFPGA. Are you ok with that?
> 
> @tpagarani It is o.k. for me as long as it does not require NDA. Can you point me to the arch files if they are already in?

@tangxifan, i am thinking that for now we will merge these changes into RS specific OpenFPGA. We can do a cleaner solution for supporting latch by default in OpenFPGA later. If you agree then I can close this one and open another PR there.

**Comment by tangxifan** [comment]
@tpagarani Make sense to me. Can you do it in a feature branch of the close-source version? I will bring the open-source part of the RS specific OpenFPGA soon (by the end of this year.

**Pull request closed without merging**
