### PR TITLE
[CICD] Added SHA tag to docker build image

### PR DESCRIPTION
**Pull request by ganeshgore**
The Docker image uploaded from master creates alternate tag with short SHA 
`openfpga-master:latest` - points to latest commit on master 
`openfpga-master:xxxxxxxx` - points to specific commit on master

### CODE REVIEW

**Comment by tangxifan** [comment]
A quick question: what is the usage of the ``openfpga-master:xxxxxxxx`` docker image?

**Comment by ganeshgore** [comment]
Great, there are 2 use cases I found
1. Incase you want to stick to some version of OpenFPGA you can do that with openfpga-master:xxxxxxxx instead of latest
2. While running CI/CD, all the actions are running in parallel, so in case when master image is getting upload other branches will use old image. I want to detect that with the tag of the latest image. (It will answer questions like in the current docker image build of current master? it will be false during master image is getting build)

**Comment by tangxifan** [comment]
> Great, there are 2 use cases I found
> 
> 1. Incase you want to stick to some version of OpenFPGA you can do that with openfpga-master:xxxxxxxx instead of latest
> 2. While running CI/CD, all the actions are running in parallel, so in case when master image is getting upload other branches will use old image. I want to detect that with the tag of the latest image. (It will answer questions like in the current docker image build of current master? it will be false during master image is getting build)

How will the obsoleted docker images be processed? Any method to control the maximum number of images in storage?

**Comment by ganeshgore** [comment]
I want to analyze for a week, that how much space it takes. as its going to store difference between previous. I don't expect it to use  much space. Based on this observation week old or month old or in worst case day old images we will delete through another schedules github action.

**Review by tangxifan — APPROVED** [review]
No problem. Remember to create an issue as a reminder.

**Pull request merged**
