### PR TITLE
Support Delay Customization in OpenFPGA Task Configuration File

### PR DESCRIPTION
**Pull request by ganeshgore**
A critical step to enable technology-independent architecture templates:
- Users can write FPGA architecture description without technology-dependent parameters, such as 
  * Delay of circuitry (required by VPR)
  * Standard cell names (required by OpenFPGA)
- OpenFPGA task script can apply these technology parameters to VPR and OpenFPGA architecture XML using the parameters defined in OpenFPGA task configuration file.
  * Users can create delay and standard cell names in yaml file format
  * Architecture files can be reused across technology

Added option to explicitly provide variable files.
+ Added test configuration

### CODE REVIEW

**Comment by tangxifan** [comment]
Any update in documentation?
Any new test case to be added?

**Comment by ganeshgore** [comment]
**Motivation** 
To minimize the frequent modification of the architecture files, It allows you to add extra variables file in the `task.conf`.
These variables can be used in the arch file, preprocessing script resolves these before passing it to the engine. 
I can be widely adopted to define `standard_cell_name`, `delay_numbers`, `pin_names` etc. 

**Test**
Already added a test_case, its already in CI/CD. We might need to add `EnvYAML` and `json` package in the build

**Comment by tangxifan** [comment]
@ganeshgore I like the idea and do think this PR should be merged. Can you update the documentation? It should be good to go then.

**Comment by ganeshgore** [comment]
Ok give me sometime there are many things pending to update in the documentation. I will update asap.

**Comment by tangxifan** [comment]
@ganeshgore You addressed Lalit's issue #145 in this PR, right?

**Comment by yashton** [comment]
@ganeshgore were you able to get the documentation @tangxifan was interested in so we can get this merged?

**Comment by tangxifan** [comment]
> @ganeshgore were you able to get the documentation @tangxifan was interested in so we can get this merged?

@yashton I have talked to @ganeshgore already. He agreed to update the documentation. However, he is now very busy with Skywater tape-out tasks. As this feature is not urgently needed for the tape-out. We can wait for another 1 week probably.

**Comment by ganeshgore** [comment]
No not yet, there are quite a few things pending to update, also I am going to address issue  https://github.com/lnis-uofu/OpenFPGA/issues/136 before updating the documentation.

I will suggest merge this pull request and create update_task_documentation issue, I will get to it next week.

**Comment by tangxifan** [comment]
> No not yet, there are quite a few things pending to update, also I am going to address issue #136 before updating the documentation.
> 
> I will suggest merge this pull request and create update_task_documentation issue, I will get to it next week.

I am cool with this plan.

**Review by tangxifan — APPROVED** [review]

**Pull request merged**
