### PR TITLE
Added RTL efpga redaction submodule

### PR DESCRIPTION
**Pull request by Lucaz97**
As discussed with Allen, doing a pull request to add RTL efpga redaction for DATE tutorial

### CODE REVIEW

**Comment by tangxifan** [comment]
@Lucaz97 Can you provide more context on the PR? I am not clear about the motivation now. For example, what the tutorial is about and why you need such change on the OpenFPGA? Thanks.

**Comment by Lucaz97** [comment]
H i, My bad, I thought it would have been managed by someone I talked with.
 We are having a tutorial at DATE 23 with Pierre Emanuel and Allen and we are going to show demos of OpenFPGA and applications for hardware redaction. My part of the demo uses the repo I added in my fork. Allen suggested merging to be able to use the binder for the tutorial.

**Review by tangxifan — COMMENTED** [review]
@Lucaz97  After reviewing your changes, I think you do not need to insert the codes to OpenFPGA, because

- You are actually using OpenFPGA to perform some Radiation-harden researches. In such case, your codes can be and should be fully separated from OpenFPGA codebase. If you are contributing new feature or apply bug fix, your code should be in the codebase.

Therefore, my suggestion is 

- Add OpenFPGA as a submodule of your github repo
- Build your binder and use it for your demo at DATE'23.

Let me know what you think.

**Comment by Lucaz97** [comment]
yes we concluded the same. thank you

**Pull request closed without merging**
