### PR TITLE
GSB dump enhancement

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR enhances data dumped by the `write_gsb_to_xml` by including rr graph node indices.

### CODE REVIEW

**Comment by tangxifan** [comment]
> @tangxifan Could you please confirm that the function I've modified in this PR dumps only the switchbox (not connection box) part of each GSB?
> https://github.com/lnis-uofu/OpenFPGA/blob/8e89da5966c97a11d9d46b9a32eea1ead5a66c92/openfpga/src/annotation/write_xml_device_rr_gsb.cpp#L22
> 
> 
> If so then can you tell me what should I do to include connection box information in the dump?

@mkurc-ant I believe the name of the function is out-of-date. It actually includes the connection box information.

https://github.com/lnis-uofu/OpenFPGA/blob/66727d0d9d1cb25d5f38e71d233766321d218ffb/openfpga/src/annotation/write_xml_device_rr_gsb.cpp#L57

You can see that it does output the IPIN-related information, which is the connection box structure

**Comment by mkurc-ant** [comment]
@tangxifan Ok, thanks for clarification. So if that is the case then this PR is ready for review.

**Comment by ganeshgore** [comment]
@mkurc-ant Can you merge changes from the current master?, that should fix the CI failing problem.

**Comment by mkurc-ant** [comment]
@ganeshgore Rebased. Let's wait for the CI.

**Comment by tangxifan** [comment]
@ganeshgore Problem remains on the docker creation. 

image

**Comment by kgugala** [comment]
@tangxifan the issue with docker is `Error: Username and password required`

looking at the CI script this action requires a password stored in repository secrets https://github.com/lnis-uofu/OpenFPGA/blob/master/.github/workflows/docker.yml#L20. Secrets are not passed to PR from outside this repo - see https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow

```
With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
```
Since this PR is opened from a fork, we cannot make this particular check to go green. Maybe the docker related tests that require logging to dockerhub should be run only for merge events (not PRs)?

**Comment by tangxifan** [comment]
@kgugala You are right. This is a problem of our CI and @ganeshgore is currently working on that. Beyond that, I think we can merge this PR regardless of the docker errors. Let me know what you think.

**Comment by ganeshgore** [comment]
@mkurc-ant Can you replace this line with 
https://github.com/antmicro/OpenFPGA/blob/c26b377056a84df69458f9a6af111da0127d2b8c/.github/workflows/build.yml#L184

`if: ${{ (github.ref == 'refs/heads/master') || (needs.change_detect.outputs.force_upload == true) }}`

**Comment by mkurc-ant** [comment]
@ganeshgore I made the change and the CI got green. Thanks.

**Review by tangxifan — APPROVED** [review]

**Pull request merged**
